name: t_core
description: t_core module

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  equatable: ^0.5.1
  shared_preferences: 0.5.3+4
  dio: ^5.0.3
  firebase_remote_config: 0.2.0+7
  firebase_analytics: ^5.0.2
  path_provider: ^2.0.14
  flutter_cache_manager: ^3.3.0
  ddi:
    path: ../packages/di

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  test: ^1.22.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
